general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../ott.dc

messagedirector:
    bind: 127.0.0.1:7199

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: ChatAgent
      id: 4681
      anonymous: false

    - class: FriendManager
      id: 4501
      anonymous: false

    - class: AvatarFriendsManager
      id: 4686
      anonymous: false

    - class: PlayerFriendsManager
      id: 4687
      anonymous: false

    - class: TTFriendsManager
      id: 4666
      anonymous: false

    - class: TTSpeedchatRelay
      id: 4712
      anonymous: false

    - class: DistributedDeliveryManager
      id: 4683
      anonymous: false

    - class: TTCodeRedemptionMgr
      id: 4695
      anonymous: false

    - class: GlobalPartyManager
      id: 4477
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:7198
      version: "TTU-version-1.0"
      #tls:
        # Required SSL configuration
       # certificate: TTU.crt # Required, a ".pem" format certificate file
        #key_file: hidden/TTU.key # Required, key for your cert file
        # Optional SSL configuration
        #chain_file: CertProvider.crt  # Specify a cert for your Intermediate CA
        #tlsv1: true   # Enables TLSv1; enabled by default;
        #sslv2: false  # Enables SSLv2; disabled by default.
        #sslv3: false  # Enables SSLv3; disabled by default.
        # CertAuthority allows you to specify a certificate authority file, or a directory
        # of CA files to be used to verify peer certificates.  When specified, connections
        # must provide a valid client certificate or be disconnected.
        #cert_authority: FooAuthority.pem
        #max_verify_depth: 2 # Defaults to 6; ignored if cert_authority is not present
              
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        foldername: ../databases/astrondb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: ../logs/events-%y%m%d_%H%M%S.log
